/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideoRouteImport } from './routes/video'
import { Route as TranscriptionStatusRouteImport } from './routes/transcription-status'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSpacesRouteImport } from './routes/app.spaces'
import { Route as AppProjectsRouteImport } from './routes/app.projects'
import { Route as AppNewRouteImport } from './routes/app.new'
import { Route as AppFinderRouteImport } from './routes/app.finder'
import { Route as AppControlRouteImport } from './routes/app.control'
import { Route as AppAskRouteImport } from './routes/app.ask'
import { Route as AppSpacesSpaceIdRouteImport } from './routes/app.spaces.$spaceId'
import { Route as AppProjectsProjectIdRouteImport } from './routes/app.projects.$projectId'
import { Route as AppOrganizationIdRouteImport } from './routes/app.organization.$id'
import { Route as AppNoteIdRouteImport } from './routes/app.note.$id'
import { Route as AppHumanIdRouteImport } from './routes/app.human.$id'
import { Route as AppAskThreadIdRouteImport } from './routes/app.ask.$threadId'
import { Route as AppNoteEventIdRouteImport } from './routes/app.note.event.$id'

const VideoRoute = VideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => rootRouteImport,
} as any)
const TranscriptionStatusRoute = TranscriptionStatusRouteImport.update({
  id: '/transcription-status',
  path: '/transcription-status',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSpacesRoute = AppSpacesRouteImport.update({
  id: '/spaces',
  path: '/spaces',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppNewRoute = AppNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppRoute,
} as any)
const AppFinderRoute = AppFinderRouteImport.update({
  id: '/finder',
  path: '/finder',
  getParentRoute: () => AppRoute,
} as any)
const AppControlRoute = AppControlRouteImport.update({
  id: '/control',
  path: '/control',
  getParentRoute: () => AppRoute,
} as any)
const AppAskRoute = AppAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => AppRoute,
} as any)
const AppSpacesSpaceIdRoute = AppSpacesSpaceIdRouteImport.update({
  id: '/$spaceId',
  path: '/$spaceId',
  getParentRoute: () => AppSpacesRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppOrganizationIdRoute = AppOrganizationIdRouteImport.update({
  id: '/organization/$id',
  path: '/organization/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppNoteIdRoute = AppNoteIdRouteImport.update({
  id: '/note/$id',
  path: '/note/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppHumanIdRoute = AppHumanIdRouteImport.update({
  id: '/human/$id',
  path: '/human/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAskThreadIdRoute = AppAskThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => AppAskRoute,
} as any)
const AppNoteEventIdRoute = AppNoteEventIdRouteImport.update({
  id: '/note/event/$id',
  path: '/note/event/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/app': typeof AppRouteWithChildren
  '/transcription-status': typeof TranscriptionStatusRoute
  '/video': typeof VideoRoute
  '/app/ask': typeof AppAskRouteWithChildren
  '/app/control': typeof AppControlRoute
  '/app/finder': typeof AppFinderRoute
  '/app/new': typeof AppNewRoute
  '/app/projects': typeof AppProjectsRouteWithChildren
  '/app/spaces': typeof AppSpacesRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/ask/$threadId': typeof AppAskThreadIdRoute
  '/app/human/$id': typeof AppHumanIdRoute
  '/app/note/$id': typeof AppNoteIdRoute
  '/app/organization/$id': typeof AppOrganizationIdRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/app/spaces/$spaceId': typeof AppSpacesSpaceIdRoute
  '/app/note/event/$id': typeof AppNoteEventIdRoute
}
export interface FileRoutesByTo {
  '/transcription-status': typeof TranscriptionStatusRoute
  '/video': typeof VideoRoute
  '/app/ask': typeof AppAskRouteWithChildren
  '/app/control': typeof AppControlRoute
  '/app/finder': typeof AppFinderRoute
  '/app/new': typeof AppNewRoute
  '/app/projects': typeof AppProjectsRouteWithChildren
  '/app/spaces': typeof AppSpacesRouteWithChildren
  '/app': typeof AppIndexRoute
  '/app/ask/$threadId': typeof AppAskThreadIdRoute
  '/app/human/$id': typeof AppHumanIdRoute
  '/app/note/$id': typeof AppNoteIdRoute
  '/app/organization/$id': typeof AppOrganizationIdRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/app/spaces/$spaceId': typeof AppSpacesSpaceIdRoute
  '/app/note/event/$id': typeof AppNoteEventIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/app': typeof AppRouteWithChildren
  '/transcription-status': typeof TranscriptionStatusRoute
  '/video': typeof VideoRoute
  '/app/ask': typeof AppAskRouteWithChildren
  '/app/control': typeof AppControlRoute
  '/app/finder': typeof AppFinderRoute
  '/app/new': typeof AppNewRoute
  '/app/projects': typeof AppProjectsRouteWithChildren
  '/app/spaces': typeof AppSpacesRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/ask/$threadId': typeof AppAskThreadIdRoute
  '/app/human/$id': typeof AppHumanIdRoute
  '/app/note/$id': typeof AppNoteIdRoute
  '/app/organization/$id': typeof AppOrganizationIdRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/app/spaces/$spaceId': typeof AppSpacesSpaceIdRoute
  '/app/note/event/$id': typeof AppNoteEventIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/app'
    | '/transcription-status'
    | '/video'
    | '/app/ask'
    | '/app/control'
    | '/app/finder'
    | '/app/new'
    | '/app/projects'
    | '/app/spaces'
    | '/app/'
    | '/app/ask/$threadId'
    | '/app/human/$id'
    | '/app/note/$id'
    | '/app/organization/$id'
    | '/app/projects/$projectId'
    | '/app/spaces/$spaceId'
    | '/app/note/event/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/transcription-status'
    | '/video'
    | '/app/ask'
    | '/app/control'
    | '/app/finder'
    | '/app/new'
    | '/app/projects'
    | '/app/spaces'
    | '/app'
    | '/app/ask/$threadId'
    | '/app/human/$id'
    | '/app/note/$id'
    | '/app/organization/$id'
    | '/app/projects/$projectId'
    | '/app/spaces/$spaceId'
    | '/app/note/event/$id'
  id:
    | '__root__'
    | '/app'
    | '/transcription-status'
    | '/video'
    | '/app/ask'
    | '/app/control'
    | '/app/finder'
    | '/app/new'
    | '/app/projects'
    | '/app/spaces'
    | '/app/'
    | '/app/ask/$threadId'
    | '/app/human/$id'
    | '/app/note/$id'
    | '/app/organization/$id'
    | '/app/projects/$projectId'
    | '/app/spaces/$spaceId'
    | '/app/note/event/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  TranscriptionStatusRoute: typeof TranscriptionStatusRoute
  VideoRoute: typeof VideoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/video': {
      id: '/video'
      path: '/video'
      fullPath: '/video'
      preLoaderRoute: typeof VideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transcription-status': {
      id: '/transcription-status'
      path: '/transcription-status'
      fullPath: '/transcription-status'
      preLoaderRoute: typeof TranscriptionStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/spaces': {
      id: '/app/spaces'
      path: '/spaces'
      fullPath: '/app/spaces'
      preLoaderRoute: typeof AppSpacesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects': {
      id: '/app/projects'
      path: '/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/new': {
      id: '/app/new'
      path: '/new'
      fullPath: '/app/new'
      preLoaderRoute: typeof AppNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/finder': {
      id: '/app/finder'
      path: '/finder'
      fullPath: '/app/finder'
      preLoaderRoute: typeof AppFinderRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/control': {
      id: '/app/control'
      path: '/control'
      fullPath: '/app/control'
      preLoaderRoute: typeof AppControlRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ask': {
      id: '/app/ask'
      path: '/ask'
      fullPath: '/app/ask'
      preLoaderRoute: typeof AppAskRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/spaces/$spaceId': {
      id: '/app/spaces/$spaceId'
      path: '/$spaceId'
      fullPath: '/app/spaces/$spaceId'
      preLoaderRoute: typeof AppSpacesSpaceIdRouteImport
      parentRoute: typeof AppSpacesRoute
    }
    '/app/projects/$projectId': {
      id: '/app/projects/$projectId'
      path: '/$projectId'
      fullPath: '/app/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/app/organization/$id': {
      id: '/app/organization/$id'
      path: '/organization/$id'
      fullPath: '/app/organization/$id'
      preLoaderRoute: typeof AppOrganizationIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/note/$id': {
      id: '/app/note/$id'
      path: '/note/$id'
      fullPath: '/app/note/$id'
      preLoaderRoute: typeof AppNoteIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/human/$id': {
      id: '/app/human/$id'
      path: '/human/$id'
      fullPath: '/app/human/$id'
      preLoaderRoute: typeof AppHumanIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ask/$threadId': {
      id: '/app/ask/$threadId'
      path: '/$threadId'
      fullPath: '/app/ask/$threadId'
      preLoaderRoute: typeof AppAskThreadIdRouteImport
      parentRoute: typeof AppAskRoute
    }
    '/app/note/event/$id': {
      id: '/app/note/event/$id'
      path: '/note/event/$id'
      fullPath: '/app/note/event/$id'
      preLoaderRoute: typeof AppNoteEventIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppAskRouteChildren {
  AppAskThreadIdRoute: typeof AppAskThreadIdRoute
}

const AppAskRouteChildren: AppAskRouteChildren = {
  AppAskThreadIdRoute: AppAskThreadIdRoute,
}

const AppAskRouteWithChildren =
  AppAskRoute._addFileChildren(AppAskRouteChildren)

interface AppProjectsRouteChildren {
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRoute
}

const AppProjectsRouteChildren: AppProjectsRouteChildren = {
  AppProjectsProjectIdRoute: AppProjectsProjectIdRoute,
}

const AppProjectsRouteWithChildren = AppProjectsRoute._addFileChildren(
  AppProjectsRouteChildren,
)

interface AppSpacesRouteChildren {
  AppSpacesSpaceIdRoute: typeof AppSpacesSpaceIdRoute
}

const AppSpacesRouteChildren: AppSpacesRouteChildren = {
  AppSpacesSpaceIdRoute: AppSpacesSpaceIdRoute,
}

const AppSpacesRouteWithChildren = AppSpacesRoute._addFileChildren(
  AppSpacesRouteChildren,
)

interface AppRouteChildren {
  AppAskRoute: typeof AppAskRouteWithChildren
  AppControlRoute: typeof AppControlRoute
  AppFinderRoute: typeof AppFinderRoute
  AppNewRoute: typeof AppNewRoute
  AppProjectsRoute: typeof AppProjectsRouteWithChildren
  AppSpacesRoute: typeof AppSpacesRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppHumanIdRoute: typeof AppHumanIdRoute
  AppNoteIdRoute: typeof AppNoteIdRoute
  AppOrganizationIdRoute: typeof AppOrganizationIdRoute
  AppNoteEventIdRoute: typeof AppNoteEventIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAskRoute: AppAskRouteWithChildren,
  AppControlRoute: AppControlRoute,
  AppFinderRoute: AppFinderRoute,
  AppNewRoute: AppNewRoute,
  AppProjectsRoute: AppProjectsRouteWithChildren,
  AppSpacesRoute: AppSpacesRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppHumanIdRoute: AppHumanIdRoute,
  AppNoteIdRoute: AppNoteIdRoute,
  AppOrganizationIdRoute: AppOrganizationIdRoute,
  AppNoteEventIdRoute: AppNoteEventIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  TranscriptionStatusRoute: TranscriptionStatusRoute,
  VideoRoute: VideoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
