// @ts-nocheck


// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getEvent(id: string) : Promise<Event | null> {
    return await TAURI_INVOKE("plugin:db|get_event", { id });
},
async listEvents(filter: ListEventFilter | null) : Promise<Event[]> {
    return await TAURI_INVOKE("plugin:db|list_events", { filter });
},
async getCalendar(calendarId: string) : Promise<Calendar | null> {
    return await TAURI_INVOKE("plugin:db|get_calendar", { calendarId });
},
async listCalendars(userId: string) : Promise<Calendar[]> {
    return await TAURI_INVOKE("plugin:db|list_calendars", { userId });
},
async upsertCalendar(calendar: Calendar) : Promise<Calendar> {
    return await TAURI_INVOKE("plugin:db|upsert_calendar", { calendar });
},
async toggleCalendarSelected(trackingId: string) : Promise<Calendar> {
    return await TAURI_INVOKE("plugin:db|toggle_calendar_selected", { trackingId });
},
async upsertSession(session: Session) : Promise<Session> {
    return await TAURI_INVOKE("plugin:db|upsert_session", { session });
},
async visitSession(id: string) : Promise<null> {
    return await TAURI_INVOKE("plugin:db|visit_session", { id });
},
async listTemplates() : Promise<Template[]> {
    return await TAURI_INVOKE("plugin:db|list_templates");
},
async upsertTemplate(template: Template) : Promise<Template> {
    return await TAURI_INVOKE("plugin:db|upsert_template", { template });
},
async deleteTemplate(id: string) : Promise<null> {
    return await TAURI_INVOKE("plugin:db|delete_template", { id });
},
async toggleTemplateFavorite(templateId: string, isFavorite: boolean) : Promise<null> {
    return await TAURI_INVOKE("plugin:db|toggle_template_favorite", { templateId, isFavorite });
},
async getFavoriteTemplates() : Promise<string[]> {
    return await TAURI_INVOKE("plugin:db|get_favorite_templates");
},
async isTemplateFavorited(templateId: string) : Promise<boolean> {
    return await TAURI_INVOKE("plugin:db|is_template_favorited", { templateId });
},
async onboardingSessionId() : Promise<string> {
    return await TAURI_INVOKE("plugin:db|onboarding_session_id");
},
async thankYouSessionId() : Promise<string> {
    return await TAURI_INVOKE("plugin:db|thank_you_session_id");
},
async listSessions(filter: ListSessionFilter | null) : Promise<Session[]> {
    return await TAURI_INVOKE("plugin:db|list_sessions", { filter });
},
async deleteSession(id: string) : Promise<null> {
    return await TAURI_INVOKE("plugin:db|delete_session", { id });
},
async getSession(filter: GetSessionFilter) : Promise<Session | null> {
    return await TAURI_INVOKE("plugin:db|get_session", { filter });
},
async setSessionEvent(sessionId: string, eventId: string | null) : Promise<null> {
    return await TAURI_INVOKE("plugin:db|set_session_event", { sessionId, eventId });
},
async sessionAddParticipant(sessionId: string, humanId: string) : Promise<null> {
    return await TAURI_INVOKE("plugin:db|session_add_participant", { sessionId, humanId });
},
async sessionRemoveParticipant(sessionId: string, humanId: string) : Promise<null> {
    return await TAURI_INVOKE("plugin:db|session_remove_participant", { sessionId, humanId });
},
async sessionListParticipants(sessionId: string) : Promise<Human[]> {
    return await TAURI_INVOKE("plugin:db|session_list_participants", { sessionId });
},
async sessionGetEvent(sessionId: string) : Promise<Event | null> {
    return await TAURI_INVOKE("plugin:db|session_get_event", { sessionId });
},
async getWords(sessionId: string) : Promise<Word[]> {
    return await TAURI_INVOKE("plugin:db|get_words", { sessionId });
},
async getWordsOnboarding() : Promise<Word[]> {
    return await TAURI_INVOKE("plugin:db|get_words_onboarding");
},
async initializeUserOnboarding() : Promise<null> {
    return await TAURI_INVOKE("plugin:db|initialize_user_onboarding");
},
async createOnboardingNote() : Promise<null> {
    return await TAURI_INVOKE("plugin:db|create_onboarding_note");
},
async getConfig() : Promise<Config> {
    return await TAURI_INVOKE("plugin:db|get_config");
},
async setConfig(config: Config) : Promise<null> {
    return await TAURI_INVOKE("plugin:db|set_config", { config });
},
async getHuman(id: string) : Promise<Human | null> {
    return await TAURI_INVOKE("plugin:db|get_human", { id });
},
async upsertHuman(human: Human) : Promise<Human> {
    return await TAURI_INVOKE("plugin:db|upsert_human", { human });
},
async listHumans(filter: ListHumanFilter | null) : Promise<Human[]> {
    return await TAURI_INVOKE("plugin:db|list_humans", { filter });
},
async getOrganization(id: string) : Promise<Organization | null> {
    return await TAURI_INVOKE("plugin:db|get_organization", { id });
},
async getOrganizationByUserId(userId: string) : Promise<Organization | null> {
    return await TAURI_INVOKE("plugin:db|get_organization_by_user_id", { userId });
},
async upsertOrganization(organization: Organization) : Promise<Organization> {
    return await TAURI_INVOKE("plugin:db|upsert_organization", { organization });
},
async listOrganizations(filter: ListOrganizationFilter | null) : Promise<Organization[]> {
    return await TAURI_INVOKE("plugin:db|list_organizations", { filter });
},
async listOrganizationMembers(organizationId: string) : Promise<Human[]> {
    return await TAURI_INVOKE("plugin:db|list_organization_members", { organizationId });
},
async listChatGroups(sessionId: string) : Promise<ChatGroup[]> {
    return await TAURI_INVOKE("plugin:db|list_chat_groups", { sessionId });
},
async listChatMessages(groupId: string) : Promise<ChatMessage[]> {
    return await TAURI_INVOKE("plugin:db|list_chat_messages", { groupId });
},
async createChatGroup(group: ChatGroup) : Promise<ChatGroup> {
    return await TAURI_INVOKE("plugin:db|create_chat_group", { group });
},
async upsertChatMessage(message: ChatMessage) : Promise<ChatMessage> {
    return await TAURI_INVOKE("plugin:db|upsert_chat_message", { message });
},
async deleteChatMessages(groupId: string) : Promise<null> {
    return await TAURI_INVOKE("plugin:db|delete_chat_messages", { groupId });
},
async createAskThread(thread: AskThread) : Promise<AskThread> {
    return await TAURI_INVOKE("plugin:db|create_ask_thread", { thread });
},
async getAskThread(threadId: string) : Promise<AskThread | null> {
    return await TAURI_INVOKE("plugin:db|get_ask_thread", { threadId });
},
async listAskThreads(userId: string, scopeType: AskScopeType | null, scopeId: string | null) : Promise<AskThread[]> {
    return await TAURI_INVOKE("plugin:db|list_ask_threads", { userId, scopeType, scopeId });
},
async archiveAskThread(threadId: string) : Promise<null> {
    return await TAURI_INVOKE("plugin:db|archive_ask_thread", { threadId });
},
async upsertAskMessage(message: AskMessage) : Promise<AskMessage> {
    return await TAURI_INVOKE("plugin:db|upsert_ask_message", { message });
},
async listAskMessages(threadId: string) : Promise<AskMessage[]> {
    return await TAURI_INVOKE("plugin:db|list_ask_messages", { threadId });
},
async upsertAskContextSnapshot(snapshot: AskContextSnapshot) : Promise<AskContextSnapshot> {
    return await TAURI_INVOKE("plugin:db|upsert_ask_context_snapshot", { snapshot });
},
async listAskContextSnapshots(threadId: string) : Promise<AskContextSnapshot[]> {
    return await TAURI_INVOKE("plugin:db|list_ask_context_snapshots", { threadId });
},
async upsertProjectFile(file: ProjectFile) : Promise<ProjectFile> {
    return await TAURI_INVOKE("plugin:db|upsert_project_file", { file });
},
async listProjectFiles(projectId: string) : Promise<ProjectFile[]> {
    return await TAURI_INVOKE("plugin:db|list_project_files", { projectId });
},
async deleteProjectFile(fileId: string) : Promise<null> {
    return await TAURI_INVOKE("plugin:db|delete_project_file", { fileId });
},
async upsertProjectFileExtraction(extraction: ProjectFileExtraction) : Promise<ProjectFileExtraction> {
    return await TAURI_INVOKE("plugin:db|upsert_project_file_extraction", { extraction });
},
async listProjectFileExtractions(projectId: string) : Promise<ProjectFileExtraction[]> {
    return await TAURI_INVOKE("plugin:db|list_project_file_extractions", { projectId });
},
async enqueueProjectKnowledgeJob(job: ProjectKnowledgeJob) : Promise<ProjectKnowledgeJob> {
    return await TAURI_INVOKE("plugin:db|enqueue_project_knowledge_job", { job });
},
async listProjectKnowledgeJobs(projectId: string) : Promise<ProjectKnowledgeJob[]> {
    return await TAURI_INVOKE("plugin:db|list_project_knowledge_jobs", { projectId });
},
async claimNextProjectKnowledgeJob() : Promise<ProjectKnowledgeJob | null> {
    return await TAURI_INVOKE("plugin:db|claim_next_project_knowledge_job");
},
async completeProjectKnowledgeJob(id: string) : Promise<ProjectKnowledgeJob> {
    return await TAURI_INVOKE("plugin:db|complete_project_knowledge_job", { id });
},
async retryProjectKnowledgeJob(id: string, errorMessage: string, runAfter: string) : Promise<ProjectKnowledgeJob> {
    return await TAURI_INVOKE("plugin:db|retry_project_knowledge_job", { id, errorMessage, runAfter });
},
async releaseProjectKnowledgeJob(id: string, runAfter: string) : Promise<ProjectKnowledgeJob> {
    return await TAURI_INVOKE("plugin:db|release_project_knowledge_job", { id, runAfter });
},
async failProjectKnowledgeJob(id: string, errorMessage: string) : Promise<ProjectKnowledgeJob> {
    return await TAURI_INVOKE("plugin:db|fail_project_knowledge_job", { id, errorMessage });
},
async reclaimStaleProjectKnowledgeJobs(staleBefore: string, maxAttempts: number) : Promise<ProjectKnowledgeJob[]> {
    return await TAURI_INVOKE("plugin:db|reclaim_stale_project_knowledge_jobs", { staleBefore, maxAttempts });
},
async upsertProjectKnowledgeSynthesis(synthesis: ProjectKnowledgeSynthesis) : Promise<ProjectKnowledgeSynthesis> {
    return await TAURI_INVOKE("plugin:db|upsert_project_knowledge_synthesis", { synthesis });
},
async getProjectKnowledgeSynthesis(projectId: string) : Promise<ProjectKnowledgeSynthesis | null> {
    return await TAURI_INVOKE("plugin:db|get_project_knowledge_synthesis", { projectId });
},
async replaceProjectSourceChunks(projectId: string, sourceType: string, sourceId: string, chunks: ProjectSourceChunk[]) : Promise<ProjectSourceChunk[]> {
    return await TAURI_INVOKE("plugin:db|replace_project_source_chunks", { projectId, sourceType, sourceId, chunks });
},
async listProjectSourceChunks(projectId: string) : Promise<ProjectSourceChunk[]> {
    return await TAURI_INVOKE("plugin:db|list_project_source_chunks", { projectId });
},
async upsertProjectSourceDigest(digest: ProjectSourceDigest) : Promise<ProjectSourceDigest> {
    return await TAURI_INVOKE("plugin:db|upsert_project_source_digest", { digest });
},
async listProjectSourceDigests(projectId: string) : Promise<ProjectSourceDigest[]> {
    return await TAURI_INVOKE("plugin:db|list_project_source_digests", { projectId });
},
async listProjectSources(projectId: string) : Promise<ProjectSource[]> {
    return await TAURI_INVOKE("plugin:db|list_project_sources", { projectId });
},
async setProjectSourceStatus(projectId: string, sessionId: string, status: ProjectSourceStatus) : Promise<null> {
    return await TAURI_INVOKE("plugin:db|set_project_source_status", { projectId, sessionId, status });
},
async addProjectSource(projectId: string, sessionId: string) : Promise<null> {
    return await TAURI_INVOKE("plugin:db|add_project_source", { projectId, sessionId });
},
async removeProjectSource(projectId: string, sessionId: string) : Promise<null> {
    return await TAURI_INVOKE("plugin:db|remove_project_source", { projectId, sessionId });
},
async upsertProjectBrief(brief: ProjectBrief) : Promise<ProjectBrief> {
    return await TAURI_INVOKE("plugin:db|upsert_project_brief", { brief });
},
async getLatestProjectBrief(projectId: string) : Promise<ProjectBrief | null> {
    return await TAURI_INVOKE("plugin:db|get_latest_project_brief", { projectId });
},
async replaceProjectBriefSources(briefId: string, sources: ProjectBriefSource[]) : Promise<ProjectBriefSource[]> {
    return await TAURI_INVOKE("plugin:db|replace_project_brief_sources", { briefId, sources });
},
async listProjectBriefSources(briefId: string) : Promise<ProjectBriefSource[]> {
    return await TAURI_INVOKE("plugin:db|list_project_brief_sources", { briefId });
},
async upsertProjectBriefRefresh(refresh: ProjectBriefRefresh) : Promise<ProjectBriefRefresh> {
    return await TAURI_INVOKE("plugin:db|upsert_project_brief_refresh", { refresh });
},
async listSpaces() : Promise<Space[]> {
    return await TAURI_INVOKE("plugin:db|list_spaces");
},
async getSpace(spaceId: string) : Promise<Space | null> {
    return await TAURI_INVOKE("plugin:db|get_space", { spaceId });
},
async createSpace(space: Space) : Promise<Space> {
    return await TAURI_INVOKE("plugin:db|create_space", { space });
},
async updateSpace(space: Space) : Promise<Space> {
    return await TAURI_INVOKE("plugin:db|update_space", { space });
},
async deleteSpace(spaceId: string) : Promise<null> {
    return await TAURI_INVOKE("plugin:db|delete_space", { spaceId });
},
async assignSessionToSpace(sessionId: string, spaceId: string) : Promise<null> {
    return await TAURI_INVOKE("plugin:db|assign_session_to_space", { sessionId, spaceId });
},
async clearSessionSpace(sessionId: string) : Promise<null> {
    return await TAURI_INVOKE("plugin:db|clear_session_space", { sessionId });
},
async listSessionsBySpace(spaceId: string, limit: number | null, search: string | null) : Promise<Session[]> {
    return await TAURI_INVOKE("plugin:db|list_sessions_by_space", { spaceId, limit, search });
},
async listIncludedSessionsBySpace(spaceId: string, limit: number | null, search: string | null) : Promise<Session[]> {
    return await TAURI_INVOKE("plugin:db|list_included_sessions_by_space", { spaceId, limit, search });
},
async listProjectsBySession(sessionId: string) : Promise<Space[]> {
    return await TAURI_INVOKE("plugin:db|list_projects_by_session", { sessionId });
},
async listAllTags() : Promise<Tag[]> {
    return await TAURI_INVOKE("plugin:db|list_all_tags");
},
async listSessionTags(sessionId: string) : Promise<Tag[]> {
    return await TAURI_INVOKE("plugin:db|list_session_tags", { sessionId });
},
async assignTagToSession(tagId: string, sessionId: string) : Promise<null> {
    return await TAURI_INVOKE("plugin:db|assign_tag_to_session", { tagId, sessionId });
},
async unassignTagFromSession(tagId: string, sessionId: string) : Promise<null> {
    return await TAURI_INVOKE("plugin:db|unassign_tag_from_session", { tagId, sessionId });
},
async upsertTag(tag: Tag) : Promise<Tag> {
    return await TAURI_INVOKE("plugin:db|upsert_tag", { tag });
},
async deleteTag(tagId: string) : Promise<null> {
    return await TAURI_INVOKE("plugin:db|delete_tag", { tagId });
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AskContextMode = "ScopedAsk" | "BriefAnswering" | "BriefGeneration" | "BriefRefresh"
export type AskContextSnapshot = { id: string; thread_id: string; message_id: string; scope_type: AskScopeType; scope_id: string | null; context_mode: AskContextMode; model_id: string | null; source_count: number; source_limit: number; sources_json: string; messages_json: string; created_at: string }
export type AskMessage = { id: string; thread_id: string; role: AskMessageRole; content: string; status: AskMessageStatus; created_at: string; model_id: string | null }
export type AskMessageRole = "User" | "Assistant" | "System"
export type AskMessageStatus = "Pending" | "Streaming" | "Complete" | "Failed"
export type AskScopeType = "Project" | "Note" | "Workspace"
export type AskThread = { id: string; user_id: string; scope_type: AskScopeType; scope_id: string | null; title: string | null; created_at: string; updated_at: string; last_message_at: string | null; archived_at: string | null }
export type Calendar = { id: string; tracking_id: string; user_id: string; platform: Platform; name: string; selected: boolean; source: string | null }
export type ChatGroup = { id: string; user_id: string; name: string | null; created_at: string; session_id: string }
export type ChatMessage = { id: string; group_id: string; created_at: string; role: ChatMessageRole; content: string; parts: string | null }
export type ChatMessageRole = "User" | "Assistant"
export type Config = { id: string; user_id: string; general: ConfigGeneral; notification: ConfigNotification; ai: ConfigAI }
export type ConfigAI = { api_base: string | null; api_key: string | null; ai_specificity: number | null; redemption_time_ms: number | null }
export type ConfigGeneral = { autostart: boolean; display_language: string; spoken_languages?: string[]; jargons?: string[]; telemetry_consent: boolean; save_recordings: boolean | null; selected_template_id: string | null; summary_language?: string; show_consent_notification?: boolean }
export type ConfigNotification = { before: boolean; auto: boolean; ignoredPlatforms: string[] | null }
export type Event = { id: string; user_id: string; tracking_id: string; calendar_id: string | null; name: string; note: string; start_date: string; end_date: string; google_event_url: string | null }
export type GetSessionFilter = { id: string } | { calendarEventId: string } | { tagId: string }
export type Human = { id: string; organization_id: string | null; is_user: boolean; full_name: string | null; email: string | null; job_title: string | null; linkedin_username: string | null }
export type ListEventFilter = ({ user_id: string; limit: number | null }) & ({ type: "simple" } | { type: "search"; query: string } | { type: "dateRange"; start: string; end: string } | { type: "not-assigned-past" })
export type ListHumanFilter = { search: [number, string] }
export type ListOrganizationFilter = { search: [number, string] }
export type ListSessionFilter = ({ user_id: string; limit: number | null }) & ({ type: "search"; query: string } | { type: "recentlyVisited" } | { type: "dateRange"; start: string; end: string } | { type: "tagFilter"; tag_ids: string[] } | { type: "needsEnhance" })
export type Organization = { id: string; name: string; description: string | null }
export type Platform = "Apple" | "Google" | "Outlook"
export type ProjectBrief = { id: string; project_id: string; markdown: string; status: ProjectBriefStatus; source_count: number; source_limit: number; source_fingerprint: string; model_id: string | null; prompt_template_version: string; error_message: string | null; generated_at: string | null; created_at: string; updated_at: string }
export type ProjectBriefRefresh = { id: string; project_id: string; brief_id: string | null; status: ProjectBriefRefreshStatus; refresh_mode: ProjectBriefRefreshMode; model_id: string | null; error_message: string | null; started_at: string; completed_at: string | null }
export type ProjectBriefRefreshMode = "Initial" | "Incremental" | "FullRebuild"
export type ProjectBriefRefreshStatus = "Running" | "Complete" | "Failed"
export type ProjectBriefSource = { brief_id: string; source_type: string; source_id: string; source_key: string; title: string; content_hash: string; created_at: string }
export type ProjectBriefStatus = "Current" | "NeedsRefresh" | "Building" | "Failed"
export type ProjectFile = { id: string; project_id: string; name: string; mime_type: string | null; size_bytes: number; storage_path: string; status: ProjectFileStatus; error_message: string | null; created_at: string; updated_at: string }
export type ProjectFileExtraction = { file_id: string; status: ProjectFileExtractionStatus; text_content: string | null; content_hash: string | null; char_count: number; error_message: string | null; extracted_at: string | null; updated_at: string }
export type ProjectFileExtractionStatus = "Pending" | "Done" | "Unsupported" | "Failed"
export type ProjectFileStatus = "Queued" | "Importing" | "Done" | "Failed"
export type ProjectKnowledgeJob = { id: string; project_id: string; job_type: ProjectKnowledgeJobType; status: ProjectKnowledgeJobStatus; dedupe_key: string; source_type: string | null; source_id: string | null; model_id: string | null; attempt_count: number; error_message: string | null; run_after: string; queued_at: string; started_at: string | null; completed_at: string | null; updated_at: string }
export type ProjectKnowledgeJobStatus = "Queued" | "Running" | "Complete" | "Failed"
export type ProjectKnowledgeJobType = "SourceDigest" | "ProjectSynthesis" | "ProjectBriefRefresh"
export type ProjectKnowledgeSynthesis = { project_id: string; source_fingerprint: string; source_count: number; model_id: string | null; key_claims_json: string; contradictions_json: string; changes_json: string; open_questions_json: string; synthesis_markdown: string; created_at: string; updated_at: string }
export type ProjectSource = { project_id: string; session_id: string; status: ProjectSourceStatus; added_by: ProjectSourceAddedBy; relevance_score: number | null; relevance_reason: string | null; reviewed_at: string | null; created_at: string; updated_at: string }
export type ProjectSourceAddedBy = "User" | "System"
export type ProjectSourceChunk = { id: string; project_id: string; source_type: string; source_id: string; chunk_index: number; source_locator: string | null; title: string; text_content: string; content_hash: string; char_count: number; source_hash: string; created_at: string; updated_at: string }
export type ProjectSourceDigest = { project_id: string; source_type: string; source_id: string; title: string; digest_source_kind: ProjectSourceDigestSourceKind; source_hash: string; summary: string; claims_json: string; entities_json: string; open_questions_json: string; decisions_json: string; risks_json: string; contradictions_json: string; digest_markdown: string; created_at: string; updated_at: string }
export type ProjectSourceDigestSourceKind = "ExistingAiNotes" | "GeneratedFromChunks" | "ManualFallback"
export type ProjectSourceStatus = "Included" | "ExcludedFromBrief" | "NeedsReview"
export type Session = { id: string; created_at: string; visited_at: string; user_id: string; calendar_event_id: string | null; title: string; raw_memo_html: string; enhanced_memo_html: string | null; auto_enhanced_memo_html: string | null; words: Word[]; record_start: string | null; record_end: string | null; pre_meeting_memo_html: string | null; source_type: string | null; source_metadata: string | null; space_id: string | null; needs_enhance: boolean }
export type Space = { id: string; name: string; description: string | null; icon_type: string; icon_value: string; icon_color: string; created_at: string; updated_at: string }
export type SpeakerIdentity = { type: "unassigned"; value: { index: number } } | { type: "assigned"; value: { id: string; label: string } }
export type Tag = { id: string; name: string }
export type Template = { id: string; user_id: string; title: string; description: string; sections: TemplateSection[]; tags: string[] }
export type TemplateSection = { title: string; description: string }
export type Word = { text: string; speaker: SpeakerIdentity | null; confidence: number | null; start_ms: number | null; end_ms: number | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
