// @ts-nocheck


// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async listCustomLlmModels() : Promise<string[]> {
    return await TAURI_INVOKE("plugin:connector|list_custom_llm_models");
},
async getCustomLlmModel() : Promise<string | null> {
    return await TAURI_INVOKE("plugin:connector|get_custom_llm_model");
},
async setCustomLlmModel(model: string) : Promise<null> {
    return await TAURI_INVOKE("plugin:connector|set_custom_llm_model", { model });
},
async getCustomLlmEnabled() : Promise<boolean> {
    return await TAURI_INVOKE("plugin:connector|get_custom_llm_enabled");
},
async setCustomLlmEnabled(enabled: boolean) : Promise<null> {
    return await TAURI_INVOKE("plugin:connector|set_custom_llm_enabled", { enabled });
},
async getCustomLlmConnection() : Promise<Connection | null> {
    return await TAURI_INVOKE("plugin:connector|get_custom_llm_connection");
},
async setCustomLlmConnection(connection: Connection) : Promise<null> {
    return await TAURI_INVOKE("plugin:connector|set_custom_llm_connection", { connection });
},
async getLocalLlmConnection() : Promise<ConnectionLLM> {
    return await TAURI_INVOKE("plugin:connector|get_local_llm_connection");
},
async getLlmConnection() : Promise<ConnectionLLM> {
    return await TAURI_INVOKE("plugin:connector|get_llm_connection");
},
async getSttConnection() : Promise<ConnectionSTT> {
    return await TAURI_INVOKE("plugin:connector|get_stt_connection");
},
async getOpenaiApiKey() : Promise<string> {
    return await TAURI_INVOKE("plugin:connector|get_openai_api_key");
},
async setOpenaiApiKey(apiKey: string) : Promise<null> {
    return await TAURI_INVOKE("plugin:connector|set_openai_api_key", { apiKey });
},
async getGroqApiKey() : Promise<string> {
    return await TAURI_INVOKE("plugin:connector|get_groq_api_key");
},
async setGroqApiKey(apiKey: string) : Promise<null> {
    return await TAURI_INVOKE("plugin:connector|set_groq_api_key", { apiKey });
},
async getGeminiApiKey() : Promise<string> {
    return await TAURI_INVOKE("plugin:connector|get_gemini_api_key");
},
async setGeminiApiKey(apiKey: string) : Promise<null> {
    return await TAURI_INVOKE("plugin:connector|set_gemini_api_key", { apiKey });
},
async getProviderSource() : Promise<string> {
    return await TAURI_INVOKE("plugin:connector|get_provider_source");
},
async setProviderSource(source: string) : Promise<null> {
    return await TAURI_INVOKE("plugin:connector|set_provider_source", { source });
},
async getOthersApiKey() : Promise<string> {
    return await TAURI_INVOKE("plugin:connector|get_others_api_key");
},
async setOthersApiKey(apiKey: string) : Promise<null> {
    return await TAURI_INVOKE("plugin:connector|set_others_api_key", { apiKey });
},
async getOthersApiBase() : Promise<string> {
    return await TAURI_INVOKE("plugin:connector|get_others_api_base");
},
async setOthersApiBase(apiBase: string) : Promise<null> {
    return await TAURI_INVOKE("plugin:connector|set_others_api_base", { apiBase });
},
async getOthersModel() : Promise<string> {
    return await TAURI_INVOKE("plugin:connector|get_others_model");
},
async setOthersModel(model: string) : Promise<null> {
    return await TAURI_INVOKE("plugin:connector|set_others_model", { model });
},
async getOpenaiModel() : Promise<string> {
    return await TAURI_INVOKE("plugin:connector|get_openai_model");
},
async setOpenaiModel(model: string) : Promise<null> {
    return await TAURI_INVOKE("plugin:connector|set_openai_model", { model });
},
async getGeminiModel() : Promise<string> {
    return await TAURI_INVOKE("plugin:connector|get_gemini_model");
},
async setGeminiModel(model: string) : Promise<null> {
    return await TAURI_INVOKE("plugin:connector|set_gemini_model", { model });
},
async getOpenrouterModel() : Promise<string> {
    return await TAURI_INVOKE("plugin:connector|get_openrouter_model");
},
async setOpenrouterModel(model: string) : Promise<null> {
    return await TAURI_INVOKE("plugin:connector|set_openrouter_model", { model });
},
async getOpenrouterApiKey() : Promise<string> {
    return await TAURI_INVOKE("plugin:connector|get_openrouter_api_key");
},
async setOpenrouterApiKey(apiKey: string) : Promise<null> {
    return await TAURI_INVOKE("plugin:connector|set_openrouter_api_key", { apiKey });
},
async getAssemblyaiApiKey() : Promise<string> {
    return await TAURI_INVOKE("plugin:connector|get_assemblyai_api_key");
},
async setAssemblyaiApiKey(apiKey: string) : Promise<null> {
    return await TAURI_INVOKE("plugin:connector|set_assemblyai_api_key", { apiKey });
},
async getSttModel() : Promise<string> {
    return await TAURI_INVOKE("plugin:connector|get_stt_model");
},
async setSttModel(model: string) : Promise<null> {
    return await TAURI_INVOKE("plugin:connector|set_stt_model", { model });
},
/**
 * Set a transient session-level STT model override. This is NOT saved to disk.
 * Used by fallback logic to switch models mid-session without touching the user's preference.
 * Clear it with `clear_stt_model_session` when the session ends.
 */
async setSttModelSession(model: string) : Promise<null> {
    return await TAURI_INVOKE("plugin:connector|set_stt_model_session", { model });
},
/**
 * Clear the transient session STT model override, restoring the user's persisted preference.
 */
async clearSttModelSession() : Promise<null> {
    return await TAURI_INVOKE("plugin:connector|clear_stt_model_session");
},
async getCloudModel() : Promise<string> {
    return await TAURI_INVOKE("plugin:connector|get_cloud_model");
},
async setCloudModel(model: string) : Promise<null> {
    return await TAURI_INVOKE("plugin:connector|set_cloud_model", { model });
},
async getAiTaskDefaults() : Promise<AiTaskDefaults> {
    return await TAURI_INVOKE("plugin:connector|get_ai_task_defaults");
},
async setAiTaskDefaults(defaults: AiTaskDefaults) : Promise<null> {
    return await TAURI_INVOKE("plugin:connector|set_ai_task_defaults", { defaults });
},
async processRecordedCloud(audioPath: string) : Promise<Word[]> {
    return await TAURI_INVOKE("plugin:connector|process_recorded_cloud", { audioPath });
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AiTaskDefaults = { project_brief_model_id: string | null; meeting_summary_model_id: string | null }
export type Connection = { api_base: string; api_key: string | null }
export type ConnectionLLM = { type: "CloudProvider"; connection: Connection } | { type: "TyprLocal"; connection: Connection } | { type: "Custom"; connection: Connection }
export type ConnectionSTT = { type: "CloudProvider"; connection: Connection } | { type: "TyprLocal"; connection: Connection }
export type SpeakerIdentity = { type: "unassigned"; value: { index: number } } | { type: "assigned"; value: { id: string; label: string } }
export type Word = { text: string; speaker: SpeakerIdentity | null; confidence: number | null; start_ms: number | null; end_ms: number | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
