const COMMANDS: &[&str] = &[
    // calendar
    "get_calendar",
    "list_calendars",
    "upsert_calendar",
    "toggle_calendar_selected",
    // session
    "onboarding_session_id",
    "thank_you_session_id",
    "visit_session",
    "upsert_session",
    "list_sessions",
    "delete_session",
    "get_session",
    "set_session_event",
    "session_add_participant",
    "session_remove_participant",
    "session_list_participants",
    "session_get_event",
    "get_words_onboarding",
    "get_words",
    "initialize_user_onboarding",
    "create_onboarding_note",
    // template
    "list_templates",
    "upsert_template",
    "delete_template",
    "get_favorite_templates",
    "toggle_template_favorite",
    "is_template_favorited",
    // event
    "get_event",
    "list_events",
    // config
    "get_config",
    "set_config",
    // user
    "get_human",
    "upsert_human",
    "list_humans",
    "delete_human",
    "upsert_organization",
    "delete_organization",
    "get_organization",
    "get_organization_by_user_id",
    "list_organizations",
    "list_organization_members",
    // chat
    "list_chat_groups",
    "list_chat_messages",
    "create_chat_group",
    "upsert_chat_message",
    "delete_chat_messages",
    // ask
    "create_ask_thread",
    "get_ask_thread",
    "list_ask_threads",
    "archive_ask_thread",
    "upsert_ask_message",
    "list_ask_messages",
    "upsert_ask_context_snapshot",
    "list_ask_context_snapshots",
    // project files
    "upsert_project_file",
    "list_project_files",
    "delete_project_file",
    "upsert_project_file_extraction",
    "list_project_file_extractions",
    "enqueue_project_knowledge_job",
    "list_project_knowledge_jobs",
    "claim_next_project_knowledge_job",
    "complete_project_knowledge_job",
    "retry_project_knowledge_job",
    "release_project_knowledge_job",
    "fail_project_knowledge_job",
    "reclaim_stale_project_knowledge_jobs",
    "upsert_project_knowledge_synthesis",
    "get_project_knowledge_synthesis",
    "replace_project_source_chunks",
    "list_project_source_chunks",
    "upsert_project_source_digest",
    "list_project_source_digests",
    // project sources
    "list_project_sources",
    "set_project_source_status",
    "add_project_source",
    "remove_project_source",
    "list_included_sessions_by_space",
    "list_projects_by_session",
    // project briefs
    "upsert_project_brief",
    "get_latest_project_brief",
    "replace_project_brief_sources",
    "list_project_brief_sources",
    "upsert_project_brief_refresh",
    // tag
    "upsert_tag",
    "delete_tag",
    "list_all_tags",
    "list_session_tags",
    "assign_tag_to_session",
    "unassign_tag_from_session",
];

fn main() {
    tauri_plugin::Builder::new(COMMANDS).build();
}
