// @ts-nocheck


// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async sentryDsn() : Promise<string> {
    return await TAURI_INVOKE("sentry_dsn");
},
async testSentryError() : Promise<null> {
    return await TAURI_INVOKE("test_sentry_error");
},
async isOnboardingNeeded() : Promise<boolean> {
    return await TAURI_INVOKE("is_onboarding_needed");
},
async setOnboardingNeeded(v: boolean) : Promise<null> {
    return await TAURI_INVOKE("set_onboarding_needed", { v });
},
async getOnboardingStep() : Promise<string | null> {
    return await TAURI_INVOKE("get_onboarding_step");
},
async setOnboardingStep(step: string) : Promise<null> {
    return await TAURI_INVOKE("set_onboarding_step", { step });
},
async getOnboardingModelSetup() : Promise<OnboardingModelSetup | null> {
    return await TAURI_INVOKE("get_onboarding_model_setup");
},
async setOnboardingModelSetup(setup: OnboardingModelSetup) : Promise<null> {
    return await TAURI_INVOKE("set_onboarding_model_setup", { setup });
},
async ensureWelcomeNote() : Promise<boolean> {
    return await TAURI_INVOKE("ensure_welcome_note");
},
async dismissWelcomeNote() : Promise<null> {
    return await TAURI_INVOKE("dismiss_welcome_note");
},
async setupDbForCloud() : Promise<null> {
    return await TAURI_INVOKE("setup_db_for_cloud");
},
async setAutostart(autostart: boolean) : Promise<null> {
    return await TAURI_INVOKE("set_autostart", { autostart });
},
async extractProjectFileText(storagePath: string, name: string, mimeType: string | null) : Promise<ProjectFileTextExtraction> {
    return await TAURI_INVOKE("extract_project_file_text", { storagePath, name, mimeType });
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type OnboardingModelSetup = { status: string; stt_model: string; llm_model: string; last_error: string | null }
export type ProjectFileTextExtraction = { text_content: string | null; char_count: number; source_units: number; extraction_kind: string; unsupported_reason: string | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
